"""Data models for pipeline monitoring."""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

logger = logging.getLogger(__name__)


class DriftType(Enum):
    """Types of drift that can be detected."""

    DATA_DRIFT = "data_drift"  # Input data distribution changes
    TARGET_DRIFT = "target_drift"  # Target/label distribution changes
    CONCEPT_DRIFT = "concept_drift"  # Relationship between features and target changes
    FEATURE_DRIFT = "feature_drift"  # Specific feature distribution changes


class AlertSeverity(Enum):
    """Alert severity levels."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


@dataclass
class DriftResult:
    """Result of a drift detection test."""

    drift_detected: bool
    drift_type: DriftType
    p_value: float
    statistic: float
    feature_name: Optional[str] = None
    threshold: float = 0.05
    timestamp: datetime = field(default_factory=datetime.utcnow)

    def is_significant(self) -> bool:
        """Check if drift is statistically significant."""
        return self.p_value < self.threshold


@dataclass
class DataQualityMetrics:
    """Data quality metrics for a batch."""

    missing_values_pct: float
    duplicate_rows_pct: float
    null_features: List[str] = field(default_factory=list)
    feature_correlations: dict = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)

    def is_healthy(
        self, max_missing_pct: float = 5.0, max_duplicate_pct: float = 1.0
    ) -> bool:
        """Check if data quality is acceptable."""
        return (
            self.missing_values_pct <= max_missing_pct
            and self.duplicate_rows_pct <= max_duplicate_pct
        )


@dataclass
class PipelineMetrics:
    """Overall pipeline metrics."""

    throughput: float  # rows/sec
    latency_p50: float  # milliseconds
    latency_p99: float  # milliseconds
    error_rate: float  # percentage
    timestamp: datetime = field(default_factory=datetime.utcnow)

    def is_healthy(
        self, min_throughput: float = 100.0, max_latency_p99: float = 5000.0
    ) -> bool:
        """Check if pipeline is healthy."""
        return (
            self.throughput >= min_throughput
            and self.latency_p99 <= max_latency_p99
            and self.error_rate < 1.0
        )


@dataclass
class MonitoringAlert:
    """Alert generated by monitoring system."""

    severity: AlertSeverity
    message: str
    alert_type: str
    metadata: dict = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class MonitoringConfig:
    """Configuration for pipeline monitoring."""

    pipeline_name: str
    drift_threshold: float = 0.05
    min_baseline_samples: int = 100
    max_missing_pct: float = 5.0
    max_duplicate_pct: float = 1.0
    metrics_port: int = 8000
    check_interval_seconds: int = 60
    features_to_monitor: List[str] = field(default_factory=list)
    categorical_features: List[str] = field(default_factory=list)
    numerical_features: List[str] = field(default_factory=list)

    def validate(self) -> bool:
        """Validate configuration."""
        if not self.pipeline_name:
            return False
        if not 0 < self.drift_threshold < 1:
            return False
        if self.min_baseline_samples < 1:
            return False
        return True
